management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    baseline-on-migrate: true
    schemas: todo
  jpa:
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        default_schema: todo
    open-in-view: false
  #    show-sql: true
  datasource:
    url: jdbc:yugabytedb://127.0.0.2:5433/yugabyte?load-balance=true
    username: yugabyte
    password: yugabyte
    driver-class-name: com.yugabyte.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: false
      leak-detection-threshold: 1

springdoc:
  api-docs:
    path: "/openapi"
    resolve-schema-properties: true
  swagger-ui:
    path: "/swagger"

#logging:
#  level:
#    com:
#      zaxxer:
#        hikari:
#          HikariConfig: DEBUG
#          pool:
#            HikariPool: DEBUG
#            PoolEntry: DEBUG


