management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    baseline-on-migrate: true
    mixed: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:yugabytedb://127.0.0.2:5433/todo
    username: todo
    password: todo
    driver-class-name: com.yugabyte.Driver

springdoc:
  api-docs:
    path: "/openapi"
    resolve-schema-properties: true
  swagger-ui:
    path: "/swagger"
